import type { CapacitorConfig } from '@capacitor/cli'

const config: CapacitorConfig = {
  appId: 'com.iqcapture.mobile',
  appName: 'IQ:capture',
  webDir: 'out',
  server: {
    // Allow HTTP connections to local dev API
    cleartext: true,
    // Allow navigation to API host
    allowNavigation: ['192.168.0.43', 'localhost', 'api.iqcapture.app'],
  },
  plugins: {
    CapacitorSQLite: {
      iosDatabaseLocation: 'Library/CapacitorDatabase',
      iosIsEncryption: false,
      androidIsEncryption: false,
    },
    StatusBar: {
      overlaysWebView: false,
      style: 'LIGHT',
      backgroundColor: '#2276aa',
    },
  },
  // Deep linking configuration
  // iOS: Add Associated Domains entitlement in Xcode (applinks:app.iqcapture.app)
  // Android: intent-filter entries are auto-generated by Capacitor
  //
  // Supported deep link patterns:
  //   iqcapture://auth/reset-password?email=...&code=...
  //   https://app.iqcapture.app/auth/reset-password?email=...&code=...
  //   https://app.iqcapture.app/auth/verify-email?email=...&code=...
}

export default config
